/**
 * excelWriter.ts
 *
 * Generates structured Excel exports from the database.
 *
 * Tabs generated by generateWeekplanExcel:
 *  1. "Voedingsplan"  — Nutrition goals + daily logged intake per week
 *  2. "Logboek"       — Body measurements per day (rows=metrics, cols=days), weekly averages
 *  3. "Feedback"      — Feedback questions + answers per week
 *  4. "Week 1", "Week 2", ... — One tab per training week with workouts and set logs
 *
 * generateExportExcel (legacy) — merges DB logs into an existing uploaded Excel source file.
 */

import XLSX from "xlsx";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { asc, eq } from "drizzle-orm";
import { db } from "@workspace/db";
import {
  exerciseLogsTable,
  nutritionEntriesTable,
  feedbackAnswersTable,
  feedbackQuestionsTable,
  plannedWorkoutsTable,
  plannedWorkoutExercisesTable,
  exerciseSetLogsTable,
  nutritionTargetsTable,
} from "@workspace/db";
import { logger } from "../lib/logger.js";
import { EXCEL_PATH, getExcelPath } from "./excelParser.js";
import { getWorkoutById } from "./dataService.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── constants ─────────────────────────────────────────────────────────────────

const DAYS_SHORT = ["ma", "di", "wo", "do", "vr", "za", "zo"] as const;
const DAYS_NL: Record<string, string> = {
  ma: "Maandag", di: "Dinsdag", wo: "Woensdag", do: "Donderdag",
  vr: "Vrijdag", za: "Zaterdag", zo: "Zondag",
  mon: "Maandag", tue: "Dinsdag", wed: "Woensdag", thu: "Donderdag",
  fri: "Vrijdag", sat: "Zaterdag", sun: "Zondag",
  maandag: "Maandag", dinsdag: "Dinsdag", woensdag: "Woensdag",
  donderdag: "Donderdag", vrijdag: "Vrijdag", zaterdag: "Zaterdag", zondag: "Zondag",
};

// Daily metrics (measured every day)
const DAILY_METRICS = [
  { key: "lichaamsgewicht", label: "Gewicht (kg)", unit: "kg" },
  { key: "kcal", label: "Calorieën (kcal)", unit: "kcal" },
  { key: "eiwittenG", label: "Eiwit (g)", unit: "g" },
  { key: "koolhydratenG", label: "Koolhydraten (g)", unit: "g" },
  { key: "vetenG", label: "Vet (g)", unit: "g" },
  { key: "waterMl", label: "Water (ml)", unit: "ml" },
  { key: "slaapUren", label: "Slaap (uren)", unit: "uren" },
  { key: "energieNiveau", label: "Energieniveau (1-10)", unit: "" },
  { key: "stressNiveau", label: "Stressniveau (1-10)", unit: "" },
  { key: "stappen", label: "Stappen", unit: "" },
  { key: "buikomvang", label: "Buikomvang (cm)", unit: "cm" },
  { key: "bilomvang", label: "Bilomvang (cm)", unit: "cm" },
] as const;

// Extended metrics (measured every ~3 weeks)
const PERIODIC_METRICS = [
  { key: "schouderOmvang", label: "Schouders (cm)", unit: "cm" },
  { key: "borstLats", label: "Borst/Lats (cm)", unit: "cm" },
  { key: "armLinks", label: "Arm links (cm)", unit: "cm" },
  { key: "armRechts", label: "Arm rechts (cm)", unit: "cm" },
  { key: "beenLinks", label: "Been links (cm)", unit: "cm" },
  { key: "beenRechts", label: "Been rechts (cm)", unit: "cm" },
  { key: "kuitLinks", label: "Kuit links (cm)", unit: "cm" },
  { key: "kuitRechts", label: "Kuit rechts (cm)", unit: "cm" },
] as const;

// ─── helpers ─────────────────────────────────────────────────────────────────

function trimCell(v: unknown): string {
  if (v === undefined || v === null) return "";
  return String(v).trim();
}

function num(v: unknown): number | null {
  if (v === null || v === undefined || v === "") return null;
  const n = Number(v);
  return isNaN(n) ? null : n;
}

function fmt(v: number | null, decimals = 1): string {
  if (v === null) return "";
  return v.toFixed(decimals);
}

function avg(values: (number | null)[]): number | null {
  const valid = values.filter((v): v is number => v !== null);
  if (valid.length === 0) return null;
  return valid.reduce((a, b) => a + b, 0) / valid.length;
}

function normalizeDayKey(day: string, dayLabel: string): string {
  const d = (day || dayLabel || "").toLowerCase().trim();
  return DAYS_NL[d] ? d : d;
}

/** Parse extra metrics from the notes JSON field of nutrition_entries */
function parseEntryMetrics(entry: { notes: string | null; [key: string]: unknown }): Record<string, number | null> {
  const result: Record<string, number | null> = {};
  if (!entry.notes) return result;
  try {
    const parsed = JSON.parse(entry.notes);
    const metrics = parsed?.metrics || parsed || {};
    for (const [k, v] of Object.entries(metrics)) {
      result[k] = num(v);
    }
  } catch {
    // ignore malformed JSON
  }
  return result;
}

/** Get a metric value from an entry (handles both direct fields and notes JSON) */
function getMetricValue(
  entry: Record<string, unknown> & { notes?: string | null },
  key: string,
  extraMetrics: Record<string, number | null>
): number | null {
  // Check direct DB field first
  if (key in entry && entry[key] !== null && entry[key] !== undefined) {
    return num(entry[key]);
  }
  // Fallback to parsed notes JSON
  return extraMetrics[key] ?? null;
}

/** Apply header styling to cells in a row */
function styleHeader(ws: XLSX.WorkSheet, row: number, fromCol: number, toCol: number) {
  for (let c = fromCol; c <= toCol; c++) {
    const addr = XLSX.utils.encode_cell({ r: row, c });
    if (!ws[addr]) continue;
    ws[addr].s = {
      font: { bold: true },
      fill: { fgColor: { rgb: "1F4E79" }, type: "pattern", patternType: "solid" },
      alignment: { horizontal: "center", wrapText: true },
    };
  }
}

function setCellValue(ws: XLSX.WorkSheet, col: number, row: number, value: string | number | null): void {
  if (value === null || value === undefined) return;
  const addr = XLSX.utils.encode_cell({ c: col, r: row });
  ws[addr] = { t: typeof value === "number" ? "n" : "s", v: value };
  const range = XLSX.utils.decode_range(ws["!ref"] || "A1:A1");
  if (row > range.e.r) range.e.r = row;
  if (col > range.e.c) range.e.c = col;
  ws["!ref"] = XLSX.utils.encode_range(range);
}

function setColWidths(ws: XLSX.WorkSheet, widths: number[]) {
  ws["!cols"] = widths.map((w) => ({ wch: w }));
}

// ─── Tab 1: Voedingsplan ──────────────────────────────────────────────────────

async function buildVoedingsplanSheet(
  clientId: string,
  nutritionTarget: typeof nutritionTargetsTable.$inferSelect | null,
  entries: (typeof nutritionEntriesTable.$inferSelect)[],
  weekNumbers: number[]
): Promise<XLSX.WorkSheet> {
  const rows: (string | number | null)[][] = [];

  // Section 1: Goals
  rows.push(["DAGELIJKSE VOEDINGSDOELEN", null, null, null, null]);
  rows.push(["", "Kcal", "Eiwit (g)", "Koolh. (g)", "Vet (g)", "Water (ml)"]);
  rows.push([
    "Doel",
    nutritionTarget?.kcal ?? "",
    nutritionTarget?.proteinG ?? "",
    nutritionTarget?.carbsG ?? "",
    nutritionTarget?.fatG ?? "",
    nutritionTarget?.waterMl ?? "",
  ]);
  rows.push([]);
  rows.push([]);

  // Section 2: Per week, per day
  const entriesByWeekDay = new Map<string, typeof nutritionEntriesTable.$inferSelect>();
  for (const e of entries) {
    const dayKey = (e.day || e.dayLabel || "").toLowerCase().trim();
    entriesByWeekDay.set(`${e.weekNumber}-${dayKey}`, e);
  }

  for (const weekNum of weekNumbers) {
    rows.push([`WEEK ${weekNum}`, null, null, null, null, null, null, null, null]);
    rows.push(["Dag", "Kcal", "Eiwit (g)", "Koolh. (g)", "Vet (g)", "Water (ml)", "Δ Kcal", "Δ Eiwit", "% Doel"]);

    const weekKcals: (number | null)[] = [];

    for (const dayShort of DAYS_SHORT) {
      const dayNL = DAYS_NL[dayShort] || dayShort;
      // Try multiple key formats
      const entry =
        entriesByWeekDay.get(`${weekNum}-${dayShort}`) ||
        entriesByWeekDay.get(`${weekNum}-${dayNL.toLowerCase()}`) ||
        null;

      const kcal = entry ? num(entry.kcal) : null;
      const eiwit = entry ? num(entry.eiwittenG) : null;
      const koolh = entry ? num(entry.koolhydratenG) : null;
      const vet = entry ? num(entry.vetenG) : null;
      const water = entry ? num(entry.waterMl) : null;

      const deltaKcal = kcal !== null && nutritionTarget?.kcal ? kcal - nutritionTarget.kcal : null;
      const deltaEiwit = eiwit !== null && nutritionTarget?.proteinG ? eiwit - nutritionTarget.proteinG : null;
      const pctDoel =
        kcal !== null && nutritionTarget?.kcal && nutritionTarget.kcal > 0
          ? Math.round((kcal / nutritionTarget.kcal) * 100)
          : null;

      weekKcals.push(kcal);
      rows.push([
        dayNL,
        kcal ?? "",
        eiwit ?? "",
        koolh ?? "",
        vet ?? "",
        water ?? "",
        deltaKcal !== null ? `${deltaKcal > 0 ? "+" : ""}${deltaKcal.toFixed(0)}` : "",
        deltaEiwit !== null ? `${deltaEiwit > 0 ? "+" : ""}${deltaEiwit.toFixed(0)}` : "",
        pctDoel !== null ? `${pctDoel}%` : "",
      ]);
    }

    // Week average row
    const avgKcal = avg(weekKcals);
    rows.push([
      "⌀ Weekgemiddelde",
      avgKcal !== null ? Math.round(avgKcal) : "",
      "",
      "",
      "",
      "",
      avgKcal !== null && nutritionTarget?.kcal
        ? `${(avgKcal - nutritionTarget.kcal) > 0 ? "+" : ""}${(avgKcal - nutritionTarget.kcal).toFixed(0)}`
        : "",
      "",
      avgKcal !== null && nutritionTarget?.kcal && nutritionTarget.kcal > 0
        ? `${Math.round((avgKcal / nutritionTarget.kcal) * 100)}%`
        : "",
    ]);
    rows.push([]);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);
  setColWidths(ws, [18, 10, 12, 12, 10, 12, 12, 12, 10]);
  return ws;
}

// ─── Tab 2: Logboek ───────────────────────────────────────────────────────────

async function buildLogboekSheet(
  entries: (typeof nutritionEntriesTable.$inferSelect)[],
  weekNumbers: number[]
): Promise<XLSX.WorkSheet> {
  const allRows: (string | number | null)[][] = [];

  // Group entries by weekNumber and day
  const entriesByWeekDay = new Map<string, typeof nutritionEntriesTable.$inferSelect>();
  for (const e of entries) {
    const dayKey = (e.day || e.dayLabel || "").toLowerCase().trim();
    entriesByWeekDay.set(`${e.weekNumber}-${dayKey}`, e);
  }

  for (const weekNum of weekNumbers) {
    // Determine if this week should show periodic metrics (every 3 weeks: week 1, 4, 7, 10, ...)
    const showPeriodic = weekNum % 3 === 1;

    // Header row: blank | Ma | Di | Wo | Do | Vr | Za | Zo | Gem.
    allRows.push([`WEEK ${weekNum}`, ...DAYS_SHORT.map((d) => DAYS_NL[d]), "⌀ Gem."]);

    // Collect entries for this week
    const weekEntries = DAYS_SHORT.map((dayShort) => {
      const dayNL = DAYS_NL[dayShort] || dayShort;
      return (
        entriesByWeekDay.get(`${weekNum}-${dayShort}`) ||
        entriesByWeekDay.get(`${weekNum}-${dayNL.toLowerCase()}`) ||
        null
      );
    });

    // Parse all extra metrics
    const weekExtraMetrics = weekEntries.map((e) => (e ? parseEntryMetrics(e) : {}));

    // Build metric rows
    const metricsToShow = showPeriodic
      ? [...DAILY_METRICS, ...PERIODIC_METRICS]
      : [...DAILY_METRICS];

    for (const metric of metricsToShow) {
      const dayValues = weekEntries.map((e, i) =>
        e ? getMetricValue(e as Record<string, unknown> & { notes?: string | null }, metric.key, weekExtraMetrics[i]) : null
      );
      const rowAvg = avg(dayValues);
      const decimals = ["kcal", "stressNiveau", "energieNiveau", "stappen"].includes(metric.key) ? 0 : 1;
      allRows.push([
        metric.label,
        ...dayValues.map((v) => (v !== null ? parseFloat(v.toFixed(decimals)) : "")),
        rowAvg !== null ? parseFloat(rowAvg.toFixed(decimals)) : "",
      ]);
    }

    allRows.push([]);
  }

  const ws = XLSX.utils.aoa_to_sheet(allRows);
  setColWidths(ws, [22, 11, 11, 11, 11, 11, 11, 11, 11]);
  return ws;
}

// ─── Tab 3: Feedback ─────────────────────────────────────────────────────────

async function buildFeedbackSheet(
  questions: (typeof feedbackQuestionsTable.$inferSelect)[],
  answers: (typeof feedbackAnswersTable.$inferSelect)[],
  weekNumbers: number[]
): Promise<XLSX.WorkSheet> {
  const rows: (string | number | null)[][] = [];

  const answerMap = new Map<string, string>();
  for (const a of answers) {
    answerMap.set(`${a.weekNumber}-${a.questionId}`, a.answer);
  }

  const sortedQuestions = [...questions].sort((a, b) => a.order - b.order);

  for (const weekNum of weekNumbers) {
    rows.push([`WEEK ${weekNum}`]);
    rows.push(["Vraag", "Antwoord"]);
    for (const q of sortedQuestions) {
      const answer = answerMap.get(`${weekNum}-${q.id}`) ?? "";
      rows.push([q.question, answer]);
    }
    rows.push([]);
  }

  if (rows.length === 0) {
    rows.push(["Nog geen feedback ingevuld."]);
  }

  const ws = XLSX.utils.aoa_to_sheet(rows);
  setColWidths(ws, [55, 70]);
  return ws;
}

// ─── Tab 4+: Training weeks ───────────────────────────────────────────────────

async function buildWeekSheets(
  wb: XLSX.WorkBook,
  workouts: (typeof plannedWorkoutsTable.$inferSelect)[],
  exercises: (typeof plannedWorkoutExercisesTable.$inferSelect)[],
  setLogs: (typeof exerciseSetLogsTable.$inferSelect)[],
  weekNumbers: number[]
): Promise<void> {
  const exercisesByWorkout = new Map<string, typeof exercises>();
  for (const ex of exercises) {
    const list = exercisesByWorkout.get(ex.workoutId) ?? [];
    list.push(ex);
    exercisesByWorkout.set(ex.workoutId, list);
  }

  const logsByExercise = new Map<string, typeof setLogs>();
  for (const log of setLogs) {
    const list = logsByExercise.get(log.plannedExerciseId) ?? [];
    list.push(log);
    logsByExercise.set(log.plannedExerciseId, list);
  }

  for (const weekNum of weekNumbers) {
    const sheetRows: (string | number | null)[][] = [];

    const weekWorkouts = workouts
      .filter((w) => w.weekNumber === weekNum)
      .sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name));

    sheetRows.push([`WEEK ${weekNum}`, null, null, null, null, null]);
    sheetRows.push([]);

    for (const workout of weekWorkouts) {
      sheetRows.push([`${workout.name}  —  ${workout.dayLabel}`, null, null, null, null, null]);
      sheetRows.push([
        "Oefening", "Sets", "Rep Range", "RPE", "Notities",
        "Set 1 Gew.", "Set 1 Reps",
        "Set 2 Gew.", "Set 2 Reps",
        "Set 3 Gew.", "Set 3 Reps",
        "Set 4 Gew.", "Set 4 Reps",
        "Set 5 Gew.", "Set 5 Reps",
        "Set 6 Gew.", "Set 6 Reps",
      ]);

      const workoutExercises = (exercisesByWorkout.get(workout.id) ?? []).sort(
        (a, b) => a.sortOrder - b.sortOrder
      );

      for (const ex of workoutExercises) {
        const logs = (logsByExercise.get(ex.id) ?? []).sort((a, b) => a.setNumber - b.setNumber);
        const row: (string | number | null)[] = [
          ex.name,
          ex.sets ?? "",
          ex.repRange ?? "",
          ex.targetRpe ?? "",
          ex.notes ?? "",
        ];
        // Up to 6 sets
        for (let s = 1; s <= 6; s++) {
          const log = logs.find((l) => l.setNumber === s);
          row.push(log?.weight ? parseFloat(String(log.weight)) : null);
          row.push(log?.reps ?? null);
        }
        sheetRows.push(row);
      }

      if (workoutExercises.length === 0) {
        sheetRows.push(["(Nog geen oefeningen toegevoegd)"]);
      }
      sheetRows.push([]);
    }

    if (weekWorkouts.length === 0) {
      sheetRows.push(["(Nog geen trainingen voor deze week)"]);
    }

    const safeSheetName = `Week ${weekNum}`.slice(0, 31);
    const ws = XLSX.utils.aoa_to_sheet(sheetRows);
    setColWidths(ws, [30, 6, 12, 6, 35, 9, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 8]);
    XLSX.utils.book_append_sheet(wb, ws, safeSheetName);
  }
}

// ─── Weekplan Export (DB-first) ────────────────────────────────────────────────

/**
 * Generates a structured Excel workbook from the database for a specific client.
 * Tabs: Voedingsplan | Logboek | Feedback | Week 1 | Week 2 | ...
 * Each client's data is fully separated via clientId.
 */
export async function generateWeekplanExcel(clientId: string): Promise<Buffer> {
  const wb = XLSX.utils.book_new();

  // Fetch all data for this client
  const [workouts, exercises, setLogs, nutritionEntries, nutritionTargetRows, questions, answers] = await Promise.all([
    db.select().from(plannedWorkoutsTable).where(eq(plannedWorkoutsTable.clientId, clientId)).orderBy(asc(plannedWorkoutsTable.weekNumber), asc(plannedWorkoutsTable.sortOrder)),
    db.select().from(plannedWorkoutExercisesTable).where(eq(plannedWorkoutExercisesTable.clientId, clientId)).orderBy(asc(plannedWorkoutExercisesTable.sortOrder)),
    db.select().from(exerciseSetLogsTable).where(eq(exerciseSetLogsTable.clientId, clientId)).orderBy(asc(exerciseSetLogsTable.weekNumber), asc(exerciseSetLogsTable.setNumber)),
    db.select().from(nutritionEntriesTable).where(eq(nutritionEntriesTable.clientId, clientId)).orderBy(asc(nutritionEntriesTable.weekNumber)),
    db.select().from(nutritionTargetsTable).where(eq(nutritionTargetsTable.clientId, clientId)).orderBy(asc(nutritionTargetsTable.sortOrder)),
    db.select().from(feedbackQuestionsTable).orderBy(asc(feedbackQuestionsTable.order)),
    db.select().from(feedbackAnswersTable).where(eq(feedbackAnswersTable.clientId, clientId)).orderBy(asc(feedbackAnswersTable.weekNumber)),
  ]);

  const nutritionTarget = nutritionTargetRows[0] ?? null;

  // Determine all relevant week numbers (union of training weeks + nutrition weeks + feedback weeks)
  const weekSet = new Set<number>([
    ...workouts.map((w) => w.weekNumber),
    ...nutritionEntries.map((e) => e.weekNumber),
    ...answers.map((a) => a.weekNumber),
  ]);
  const weekNumbers = Array.from(weekSet).sort((a, b) => a - b);

  if (weekNumbers.length === 0) {
    const emptySheet = XLSX.utils.aoa_to_sheet([["Nog geen data beschikbaar voor deze klant."]]);
    XLSX.utils.book_append_sheet(wb, emptySheet, "Overzicht");
    logger.info({ clientId }, "No data found for weekplan export");
    return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
  }

  // Build all sheets
  const [voedingsSheet, logboekSheet, feedbackSheet] = await Promise.all([
    buildVoedingsplanSheet(clientId, nutritionTarget, nutritionEntries, weekNumbers),
    buildLogboekSheet(nutritionEntries, weekNumbers),
    buildFeedbackSheet(questions, answers, weekNumbers),
  ]);

  XLSX.utils.book_append_sheet(wb, voedingsSheet, "Voedingsplan");
  XLSX.utils.book_append_sheet(wb, logboekSheet, "Logboek");
  XLSX.utils.book_append_sheet(wb, feedbackSheet, "Feedback");

  // Build one sheet per training week
  const trainingWeekNumbers = Array.from(new Set(workouts.map((w) => w.weekNumber))).sort((a, b) => a - b);
  await buildWeekSheets(wb, workouts, exercises, setLogs, trainingWeekNumbers);

  logger.info({ clientId, weeks: weekNumbers.length, trainingWeeks: trainingWeekNumbers.length }, "Weekplan Excel generated");
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

// ─── Legacy Export (merges logs into source Excel) ────────────────────────────

function getCellValue(sheet: XLSX.WorkSheet, col: number, row: number): string {
  const addr = XLSX.utils.encode_cell({ c: col, r: row });
  return trimCell(sheet[addr]?.v);
}

function setCellValueLegacy(sheet: XLSX.WorkSheet, col: number, row: number, value: string | number): void {
  const addr = XLSX.utils.encode_cell({ c: col, r: row });
  sheet[addr] = { t: typeof value === "number" ? "n" : "s", v: value };
  const range = XLSX.utils.decode_range(sheet["!ref"] || "A1:A1");
  if (row > range.e.r) range.e.r = row;
  if (col > range.e.c) range.e.c = col;
  sheet["!ref"] = XLSX.utils.encode_range(range);
}

async function writeExerciseLogsToWeekSheets(wb: XLSX.WorkBook, clientId: string): Promise<void> {
  const allLogs = await db.select().from(exerciseLogsTable).where(eq(exerciseLogsTable.clientId, clientId));
  if (allLogs.length === 0) return;

  const byWeek = new Map<number, typeof allLogs>();
  for (const log of allLogs) {
    const list = byWeek.get(log.weekNumber) ?? [];
    list.push(log);
    byWeek.set(log.weekNumber, list);
  }

  for (const [weekNumber, logs] of byWeek) {
    const sheetName = wb.SheetNames.find((n) => {
      const lower = n.toLowerCase();
      return lower.includes("upperlower") || lower.includes("upper lower") || lower.includes("deload");
    });
    if (!sheetName) continue;

    const sheet = wb.Sheets[sheetName];
    const rows: string[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", raw: false });

    for (const log of logs) {
      const workout = getWorkoutById(log.workoutId, clientId);
      const exerciseName = workout?.exercises.find((e) => e.id === log.exerciseId)?.name;
      if (!exerciseName) continue;

      const exerciseNameLower = exerciseName.toLowerCase().trim();
      for (let ri = 0; ri < rows.length; ri++) {
        const colB = trimCell(rows[ri][1]);
        const cellBName = colB.replace(/^[A-Za-z]\s*:\s*/, "").toLowerCase().trim();
        if (cellBName && cellBName === exerciseNameLower) {
          const weights = log.weight ? log.weight.split(",").map((s) => s.trim()) : [];
          for (let si = 0; si < 5 && si < weights.length; si++) {
            const w = parseFloat(weights[si]);
            if (!isNaN(w) && w > 0) setCellValueLegacy(sheet, 3 + si, ri, w);
          }
          break;
        }
      }
    }
  }
}

async function writeNutritionToProgressie(wb: XLSX.WorkBook, clientId: string): Promise<void> {
  const entries = await db.select().from(nutritionEntriesTable).where(eq(nutritionEntriesTable.clientId, clientId));
  if (entries.length === 0) return;

  const sheetName = wb.SheetNames.find((n) => /progressie/i.test(n));
  if (!sheetName) return;

  const sheet = wb.Sheets[sheetName];
  const rows: string[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", raw: false });

  const entriesMap = new Map<string, typeof entries[0]>();
  for (const entry of entries) {
    const dayNL = DAYS_NL[entry.day] || entry.dayLabel || entry.day;
    entriesMap.set(`${entry.weekNumber}-${dayNL.toLowerCase()}`, entry);
  }

  let currentWeekNumber: number | null = null;
  let colGewicht = 1, colKcal = 2, colBuik = 3, colHeup = 4;
  let colKracht = 5, colEnergie = 6, colSlaap = 7, colStress = 8, colStappen = 9;

  for (let ri = 0; ri < rows.length; ri++) {
    const row = rows[ri];
    const col0 = trimCell(row[0]);
    if (!col0) continue;
    const weekMatch = col0.match(/^week\s+(\d+)$/i);
    if (weekMatch) {
      currentWeekNumber = parseInt(weekMatch[1], 10);
      const headerRow = row.map((c) => trimCell(c).toLowerCase());
      for (let ci = 1; ci < headerRow.length; ci++) {
        const h = headerRow[ci];
        if (h === "gewicht") colGewicht = ci;
        else if (h.includes("kcal")) colKcal = ci;
        else if (h.includes("buikomvang")) colBuik = ci;
        else if (h.includes("heupomvang")) colHeup = ci;
        else if (h.includes("krachtniveau")) colKracht = ci;
        else if (h.includes("energieniveau")) colEnergie = ci;
        else if (h === "slaap") colSlaap = ci;
        else if (h === "stress") colStress = ci;
        else if (h.includes("stappen")) colStappen = ci;
      }
      continue;
    }
    if (!currentWeekNumber) continue;
    const entry = entriesMap.get(`${currentWeekNumber}-${col0.toLowerCase()}`);
    if (entry) {
      const extras = parseEntryMetrics(entry);
      if (entry.lichaamsgewicht) setCellValueLegacy(sheet, colGewicht, ri, parseFloat(String(entry.lichaamsgewicht)));
      if (entry.kcal) setCellValueLegacy(sheet, colKcal, ri, parseFloat(String(entry.kcal)));
      if (extras.buikomvang) setCellValueLegacy(sheet, colBuik, ri, extras.buikomvang);
      if (extras.heupomvang) setCellValueLegacy(sheet, colHeup, ri, extras.heupomvang);
      if (entry.energieNiveau) setCellValueLegacy(sheet, colEnergie, ri, entry.energieNiveau);
      if (entry.slaapUren) setCellValueLegacy(sheet, colSlaap, ri, parseFloat(String(entry.slaapUren)));
      if (entry.stressNiveau) setCellValueLegacy(sheet, colStress, ri, entry.stressNiveau);
    }
  }
}

async function writeFeedbackAnswers(wb: XLSX.WorkBook, clientId: string): Promise<void> {
  const answers = await db.select().from(feedbackAnswersTable).where(eq(feedbackAnswersTable.clientId, clientId));
  if (answers.length === 0) return;
  const sheetName = wb.SheetNames.find((n) => /feedback/i.test(n));
  if (!sheetName) return;
  const sheet = wb.Sheets[sheetName];
  const rows: string[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", raw: false });
  const byWeekQ = new Map<string, string>();
  for (const ans of answers) {
    byWeekQ.set(`${ans.weekNumber}-${ans.questionId}`, ans.answer);
  }
  const existingKeys = new Set<string>();
  for (let ri = 1; ri < rows.length; ri++) {
    const wk = trimCell(rows[ri][7]);
    const qid = trimCell(rows[ri][8]);
    if (wk && qid) existingKeys.add(`${wk}-${qid}`);
  }
  const range = XLSX.utils.decode_range(sheet["!ref"] || "A1:A1");
  let nextRow = range.e.r + 1;
  for (const [key, answer] of byWeekQ) {
    if (existingKeys.has(key)) continue;
    const [weekStr, qidStr] = key.split("-");
    setCellValueLegacy(sheet, 7, nextRow, parseInt(weekStr));
    setCellValueLegacy(sheet, 8, nextRow, parseInt(qidStr));
    setCellValueLegacy(sheet, 9, nextRow, answer);
    nextRow++;
  }
}

/**
 * Legacy export: merges DB data back into an existing uploaded Excel source file.
 * Falls back to generating from scratch if no source file exists.
 */
export async function generateExportExcel(clientId: string): Promise<Buffer> {
  let wb: XLSX.WorkBook;

  const clientExcelPath = getExcelPath(clientId);
  const sourcePath = fs.existsSync(clientExcelPath)
    ? clientExcelPath
    : fs.existsSync(EXCEL_PATH)
    ? EXCEL_PATH
    : null;

  if (sourcePath) {
    wb = XLSX.readFile(sourcePath);
    logger.info({ clientId, sourcePath }, "Loaded existing Excel file for legacy export");
  } else {
    wb = XLSX.utils.book_new();
    logger.info({ clientId }, "No source Excel found, generating from DB");
    return generateWeekplanExcel(clientId);
  }

  try { await writeExerciseLogsToWeekSheets(wb, clientId); } catch (err) { logger.warn({ err }, "Failed to write exercise logs"); }
  try { await writeNutritionToProgressie(wb, clientId); } catch (err) { logger.warn({ err }, "Failed to write nutrition"); }
  try { await writeFeedbackAnswers(wb, clientId); } catch (err) { logger.warn({ err }, "Failed to write feedback"); }

  logger.info({ clientId }, "Legacy Excel export generated");
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
